# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f99c2be4e64aa0b0d0699d5de5531985dce221e4f333b7061bb577dac4a07ecb0cea738166af0703d6958797930d73620966df0dacf468c350c60d74bc48114

test:
  secret_key_base: 47274910882299136ade53436bd885eebb734ecf83c961dfe35868822ac280f17f5e94dee43fe85e13fbf3a1c310b901aa50d2a2a7687e275f037e22a5829486

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
